name: 'Terragrunt Plan'
on:
  pull_request:
    branches:
      - main

env:
  tg_version: '0.67.0'
  tf_version: '1.8.5'
  working_dir: 'teratest'
  GITHUB_TOKEN: ${{ secrets.TRF }}

permissions:
  actions: write       # Necessary to cancel workflow executions
  checks: write        # Necessary to write reports
  pull-requests: write # Necessary to comment on PRs
  contents: read
  packages: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: 'Terragrunt Check and Plan'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      # - name: Check HCL
      #   uses: gruntwork-io/terragrunt-action@v2
      #   with:
      #     tf_version: ${{env.tf_version}}
      #     tg_version: ${{env.tg_version}}
      #     tg_dir: ${{env.working_dir}}
      #     tg_command: 'hclfmt --terragrunt-check'
      
      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{env.tf_version}}
          tg_version: ${{env.tg_version}}
          tg_dir: ${{env.working_dir}}        
          tg_command: 'plan'
          tg_comment: 1
